// Generated by CoffeeScript 1.6.3
j3r.conf = {
  categories: {
    'cat-a': {
      'cat-a_a': 'Bydliste',
      'cat-a_b': 'Obchody'
    },
    'cat-a_b': {
      'cat-a_b_a': 'Zradlo',
      'cat-a_b_b': 'Stavba'
    }
  },
  markers: {
    'ledce': {
      cat: 'cat-a_a',
      title: 'Ledce',
      pos: [49.820708, 13.328369]
    },
    'sbks': {
      cat: 'cat-a_a',
      title: 'Socialbakers',
      pos: [49.754044, 13.378576]
    },
    'kaufland_locho': {
      cat: 'cat-a_b_a',
      title: 'Kaufland',
      pos: [49.753670, 13.376709]
    },
    'bauhaus_bory': {
      cat: 'cat-a_b_b',
      title: 'Bauhaus',
      pos: [49.729528, 13.350264]
    },
    'chelcickeho': {
      cat: 'cat-a_acat-a_b',
      title: 'Chelcickeho',
      pos: [49.739413, 13.365165]
    }
  }
};
