// Generated by CoffeeScript 1.6.3
j3r.conf = {
  'categories': {
    'init': {
      'cat-a': 'cat-a',
      'cat-b': 'cat-b'
    },
    'list': {
      'cat-a': {
        'cat-a_a': 'Plzensky kraj',
        'cat-a_b': 'Prazsky kraj'
      },
      'cat-a_a': {
        'cat-a_a_a': 'Plzen',
        'cat-a_a_b': 'Venkov'
      },
      'cat-a_b': {
        'cat-a_b_a': 'Praha'
      },
      'cat-b': {
        'cat-b_a': 'obchod',
        'cat-b_b': 'jiny'
      }
    },
    'titles': {
      'cat-a': 'kraj',
      'cat-a_a': 'mesto',
      'cat-a_b': 'mesto',
      'cat-b': 'typ mista'
    }
  },
  'markers': {
    'ledce': {
      cat: 'cat-a_a_bcat-b_b',
      title: 'Ledce',
      pos: [49.820708, 13.328369]
    },
    'sbks': {
      cat: 'cat-a_a_acat-b_b',
      title: 'Socialbakers',
      pos: [49.754044, 13.378576]
    },
    'kaufland_locho': {
      cat: 'cat-a_a_acat-b_a',
      title: 'Kaufland',
      pos: [49.753670, 13.376709]
    },
    'bauhaus_bory': {
      cat: 'cat-a_a_acat-b_a',
      title: 'Bauhaus',
      pos: [49.729528, 13.350264]
    },
    'chelcickeho': {
      cat: 'cat-a_a_acat-b_b',
      title: 'Chelcickeho',
      pos: [49.739413, 13.365165]
    },
    'vaclav': {
      cat: 'cat-a_b_acat-b_b',
      title: 'Vaclav',
      pos: [50.080195, 14.429101]
    }
  }
};
