// Generated by CoffeeScript 1.6.3
j3r.InfoWindows = (function() {
  function InfoWindows(markerInfos) {
    this.markerInfos = markerInfos;
    this.markersInfoWindows = {};
    return;
  }

  InfoWindows.prototype.getInfoWindow = function(markerId) {
    if (this.markersInfoWindows[markerId] == null) {
      this.markersInfoWindows[markerId] = this.generateInfoWindow(this.markerInfos[markerId]);
    }
    return this.markersInfoWindows[markerId];
  };

  InfoWindows.prototype.generateInfoWindow = function(markerInfo) {
    var contentString, infowindow;
    contentString = '<h3>' + markerInfo['title'] + '</h3>\
			<p>' + markerInfo['info'] + '</p>';
    return infowindow = new google.maps.InfoWindow({
      content: contentString
    });
  };

  return InfoWindows;

})();

j3r.InfoWindows.create = function() {
  return new j3r.InfoWindows(j3r.conf['markers']);
};
