// Generated by CoffeeScript 1.6.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

j3r.InfoWindows = (function() {
  function InfoWindows(markerInfos) {
    this.markerInfos = markerInfos;
    this.hideAllMarkersInfoWindows = __bind(this.hideAllMarkersInfoWindows, this);
    this.markersInfoWindows = {};
    return;
  }

  InfoWindows.prototype.getInfoWindow = function(markerId) {
    if (this.markersInfoWindows[markerId] == null) {
      this.markersInfoWindows[markerId] = this.generateInfoWindow(markerId, this.markerInfos[markerId]);
    }
    return this.markersInfoWindows[markerId];
  };

  InfoWindows.prototype.hideAllMarkersInfoWindows = function() {
    var key, markerInfoWindow, _ref;
    _ref = this.markersInfoWindows;
    for (key in _ref) {
      markerInfoWindow = _ref[key];
      markerInfoWindow.close();
    }
  };

  InfoWindows.prototype.generateInfoWindow = function(markerId) {
    var infowindow;
    return infowindow = new google.maps.InfoWindow({
      content: this.generateInfoWindowContent(markerId)
    });
  };

  InfoWindows.prototype.generateInfoWindowContent = function(markerId) {
    var categories, contentString;
    categories = this.markerInfos[markerId];
    contentString = '<div class="info-window-wrapper">\
			<h3>' + this.markerInfos[markerId]['title'] + '</h3>\
			<div class="info-window-text main-type"><strong>Typ:&nbsp</strong> \
			' + j3r.helpers.getCategoryInfo(markerId, 1) + '</div>';
    if (j3r.helpers.getCategoryInfo(markerId, 2) !== '') {
      contentString += '<div class="info-window-text sub-type"><strong>Oddělení:&nbsp;</strong>' + j3r.helpers.getCategoryInfo(markerId, 2, ', ') + '</div>';
    }
    if ((this.markerInfos[markerId]['gal'] == null) + '\
			</div>') {
      return contentString += '<div  class="info-window-text info">' + this.markerInfos[markerId]['info'] + '</div>\
			<div class="info-window-text adress"">Adresa:&nbsp;' + this.markerInfos[markerId]['adress'] + '</div>\
			' + this.generateInfoWindowGallery(markerId, this.markerInfos[markerId]['gal']);
    }
  };

  InfoWindows.prototype.generateInfoWindowGallery = function(folder, galleryInfo) {
    var linkToFolder, output, picLink, pos;
    output = '<div class="info-window-wrapper-gal ' + folder + '">';
    linkToFolder = j3r.conf['settings']['pathToInfoWindowPics'] + folder + '/';
    for (pos in galleryInfo) {
      picLink = galleryInfo[pos];
      output += '<a href="' + linkToFolder + picLink.replace('_sm', '') + '"\
			 class="colorboxGallery pic-gal cboxElement" rel="gal">\
		    <img class="link-outline" src="' + linkToFolder + picLink + '" alt="">\
			</a>';
    }
    return output + '</div>';
  };

  return InfoWindows;

})();

j3r.InfoWindows.create = function() {
  return new j3r.InfoWindows(j3r.conf['markers']);
};
