// Generated by CoffeeScript 1.6.3
var url,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

url = '../';

j3r.Map = (function() {
  function Map(position, mapCanvas, mapOptions, options) {
    var optionKey, optionValue;
    this.position = position;
    this.mapCanvas = mapCanvas;
    this.mapOptions = mapOptions;
    if (options == null) {
      options = null;
    }
    this.addMarker = __bind(this.addMarker, this);
    this.addMarkerByType = __bind(this.addMarkerByType, this);
    this.addMarkers = __bind(this.addMarkers, this);
    if (options != null) {
      for (optionValue in options) {
        optionKey = options[optionValue];
        this.mapOptions[optionKey] = optionValue;
      }
    }
    this.map = new google.maps.Map(this.mapCanvas, this.mapOptions);
    return;
  }

  Map.prototype.init = function() {
    google.maps.event.addDomListener(window, 'load', this.map);
  };

  Map.prototype.getMap = function() {
    return this.map;
  };

  Map.prototype.addMarkers = function(type) {
    if (type == null) {
      type = null;
    }
    if (type != null) {
      if (this.poi[type] != null) {
        this.addMarkerByType(type);
      }
    } else {
      for (type in this.poi) {
        this.addMarkerByType(type);
      }
    }
  };

  Map.prototype.addMarkerByType = function(type) {
    var pos, _i, _ref;
    for (pos = _i = 0, _ref = this.poi[type].length + 1; 0 <= _ref ? _i <= _ref : _i >= _ref; pos = 0 <= _ref ? ++_i : --_i) {
      this.addMarker(type, pos);
    }
  };

  Map.prototype.addMarker = function(type, pos) {
    var marker, markerInfo;
    if (this.markers[type] == null) {
      this.markers[type] = [];
    }
    markerInfo = this.poi[type][pos];
    if (markerInfo != null) {
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(markerInfo['pos']),
        map: this.map,
        title: markerInfo['name']
      });
      this.markers[type].push(marker);
    }
  };

  return Map;

})();

j3r.Map.create = function() {
  var mapCanvas, mapOptions, position;
  position = [49.740290, 13.365370];
  mapCanvas = document.getElementById('map-canvas');
  mapOptions = {
    center: new google.maps.LatLng(position[0], position[1]),
    zoom: 11,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  return new j3r.Map(position, mapCanvas, mapOptions);
};
