// Generated by CoffeeScript 1.6.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

j3r.Search = (function() {
  Search.startSearchFrom = j3r.conf['settings']['startSearchFromMinCharCount'];

  function Search(markersInfo, searchList) {
    this.markersInfo = markersInfo;
    this.searchList = searchList;
    this.search = __bind(this.search, this);
    this.wrapper = $(j3r.conf['settings']['el_searchResults']);
    this.actualList = {};
    this.actualLetters = '';
  }

  Search.prototype.search = function(key) {
    var item, itemKey, keyAct, searchIn, _ref, _ref1;
    if (key === '' || (key.length === (j3r.Search.startSearchFrom - 1) && this.actualLetters.length === j3r.Search.startSearchFrom)) {
      this.actualLetters = '';
      this.actualList = {};
      this.renderResults();
    } else {
      key = j3r.helpers.getTransformedText(key, false);
      if (key < this.actualLetters.length || key.length >= j3r.Search.startSearchFrom) {
        if (key.length > this.actualLetters.length && !jQuery.isEmptyObject(this.actualList)) {
          _ref = this.actualList;
          for (keyAct in _ref) {
            item = _ref[keyAct];
            if (this.searchList[keyAct].indexOf(key) === -1) {
              delete this.actualList[keyAct];
            }
          }
        } else {
          this.actualList = {};
          _ref1 = this.searchList;
          for (itemKey in _ref1) {
            searchIn = _ref1[itemKey];
            if (searchIn.indexOf(key) !== -1) {
              this.actualList[itemKey] = this.getItem(itemKey);
            }
          }
        }
        this.actualLetters = key;
        this.renderResults();
      }
    }
  };

  Search.prototype.renderResults = function() {
    var item, itemKey, _ref;
    this.wrapper.empty();
    _ref = this.actualList;
    for (itemKey in _ref) {
      item = _ref[itemKey];
      this.wrapper.append(item);
    }
  };

  Search.prototype.getItem = function(key) {
    var itemHtml, itemInfo;
    itemInfo = this.markersInfo[key];
    return itemHtml = '<a onclick="app.showInfoWindow(\'' + key + '\')"><div class="' + j3r.conf['settings']['el_searchResultItem'] + '"><strong>\
      ' + itemInfo['title'] + '</strong>(' + j3r.helpers.getCategoryInfoToString(itemInfo['cat'], 'cat-a') + ')</div></a>';
  };

  Search.prototype.generateListOfMarkers = function(markers) {
    var markerId, markerInfo, text;
    for (markerId in markers) {
      markerInfo = markers[markerId];
      text = markerInfo['title'] + j3r.helpers.getCategoryInfoToString(markerInfo['cat'], 'cat-a', '') + markerInfo['info'];
      text = j3r.helpers.getTransformedText(text, false);
      console.log("'" + markerId + "':'" + text + "'");
    }
  };

  return Search;

})();

j3r.Search.create = function() {
  return new j3r.Search(j3r.conf['markers'], j3r.conf['searchList']);
};

j3r.Search.callGenerateListOfMarkers = function() {
  var search;
  search = new j3r.Search({});
  search.generateListOfMarkers(j3r.conf['markers'], j3r.conf['categories']['list']);
};
